### ISSUE TITLE
Register for API Keys - Trakt

### ISSUE THREAD

**Issue by sucheta90** [hotperformancehorses/entertainment-finder#1]
# Register for API keys

## User story
As a developer/ contributor to the project, everyone needs to signup for the API key. [Trakt](https://trakt.tv/auth/signin)

## Acceptance Criteria
It is done when everyone has their own API keys.

**Comment by hotperformancehorses** [comment]
I signed up for an account at Trakt, but I don't see where I need to do anything specifically for the API except where it says build a new app and we're not to that point yet I imagine, or are we? Somebody point me in the right direction. Please. Lol

**Comment by sucheta90** [comment]
Hey! Me having the same issue with trakt 😢
